### ISSUE TITLE
Message parsing error

### ISSUE THREAD

**Issue by Plutoject** [ClusterWS/ClusterWS-Client-JS#42]
### Submitting

- [x] Bug
- [ ] Question
- [ ] Suggetion
- [ ] Other

### Details

1. 3.0.4 client, 3.0.5 server
2. Ubuntu 17.10
3. Hi, I updated from version 2.x -> to 3.x (Server and client). When i restarting my app I got an error in the console on the Chrome "TypeError: t.subarray is not a function
    at uint8ArrayToString (index.js:9)
    at WebSocket.websocket.onmessage (index.js:141)"  
As I understood this error appears when we send message to the client.
**Example server side**: socket.send('eventName', 'test message');

**Comment by goriunov** [comment]
Thank for this error message, i have not notice this small part as i was testing with binary enabled. Should be working fine with new release client 3.0.5

**Comment by Plutoject** [comment]
You're welcome. Tnx for good lib.
